service: aws-python-http-api-project
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.9

functions:
  hello_custom:
    handler: handler.hello
    events:
      - httpApi:
          path: /greetings
          method: get
